apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: eeyore-l2-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      lb-ip-pool: eeyore-pool
  loadBalancerIPs: true
