apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress-l2-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
  loadBalancerIPs: true
